export const SET_PLAYING = 'SET_PLAYING'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE = 'SET_SEQUENCE'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENTINDEX = 'SET_CURRENTINDEX'
